{
  "$schema": "node_modules/wrangler/config-schema.json",
  "name": "<urlshortener.andrearey.workers.dev>",
  "main": "src/index.ts",
  "compatibility_date": "2025-02-04",
  "observability": {
    "enabled": true
  },

  "kv_namespaces": [
    {
      "binding": "KV",
      "id": "<vcf_urls>"
    }
  ]
}
